cmake_minimum_required(VERSION 3.25.1)
project(calki C)

set(CMAKE_C_STANDARD 11)

add_executable(calki
        main.c
        functions.c
        interface.c
        heders/interface.h
        utils.c
        heders/utils.h
        heders/
        heders/functions.h
        methods.c
        heders/methods.h
        main.c
        timer.c
        heders/timer.h)
